# Generated by Django 4.0 on 2022-02-21 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='pin_code',
        ),
    ]
