# Generated by Django 3.0.3 on 2022-02-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='class_time',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='registration_number',
            field=models.CharField(default=(10, 0, 0), max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooms',
            name='vehicle_type',
            field=models.CharField(default='Perodua myvi', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
