# Generated by Django 3.0.3 on 2022-02-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20220210_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='registration_number',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
